[workspace]
channels = ["conda-forge","aihabitat"]
name = "cov"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
shortuuid = ">=1.0.13,<2"
jinja2 = ">=3.1.6,<4"
python = "3.9.*"
tqdm = ">=4.67.1,<5"
habitat-sim = "==0.3.3"
headless = ">=2.0"
numpy = ">=1.26.4,<2"
socksio = ">=1.0.0,<2"
ipykernel = ">=6.30.1,<7"

[pypi-dependencies]
python-dotenv = ">=1.2.1, <2"
trimesh = ">=4.9.0, <5"
pyrender = ">=0.1.45, <0.2"
hydra-core = ">=1.3.2, <2"
litellm = ">=1.80.0, <2"
natsort = ">=8.4.0, <9"
